# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PARAMETERS <- function(n, d, iteration) {
    .Call(`_MCGK_PARAMETERS`, n, d, iteration)
}

CGKPRESET <- function(n, d, parameters) {
    .Call(`_MCGK_CGKPRESET`, n, d, parameters)
}

CGK <- function(X, n, d, preset) {
    .Call(`_MCGK_CGK`, X, n, d, preset)
}

MCGK <- function(D, n, d, testpreset) {
    .Call(`_MCGK_MCGK`, D, n, d, testpreset)
}

MCGKTEST <- function(D, n, d, testpreset, iteration) {
    .Call(`_MCGK_MCGKTEST`, D, n, d, testpreset, iteration)
}

